CREATE TABLE [dbo].[SalesOrderLines]
(
	[SalesOrderId] int NOT NULL,
	[SalesOrderLineNo] int NOT NULL,
	[ProductId] INT NOT NULL,
	[OrderedQty] int NOT NULL,
	[RecivedQty] int NULL,
	[PriceTypeId] int NOT NULL,
	[PurchaseOrderPrice] decimal (15, 5) NOT NULL DEFAULT ((1)),
	[ExpectedDate] datetime NULL,
	[DeliveryDate] datetime NULL,
	[DiscountTypeId] INT NOT NULL  DEFAULT ((1)),
	[DiscountValue] INT NULL,
	[EntryAuthor] varchar (32)  NOT NULL  DEFAULT (SUSER_SNAME()),
	[EntryDate] datetime NOT NULL  DEFAULT (GETDATE()),
	[LastAuthor] varchar (32)  NOT NULL  DEFAULT (SUSER_SNAME()),
	[LastUpdate] datetime NOT NULL  DEFAULT (GETDATE()),
	CONSTRAINT [PK_SalesOrderLines] PRIMARY KEY CLUSTERED ([SalesOrderId],[SalesOrderLineNo]),
	CONSTRAINT FK_Products_SalesOrderLines FOREIGN KEY ([ProductId])  REFERENCES Products([ProductId]),
	CONSTRAINT FK_DiscountTypes_SalesOrderLines FOREIGN KEY (DiscountTypeId)  REFERENCES DiscountTypes([DiscountTypeId]),
)