//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptPlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiptPlans()
        {
            this.ReceiptPlanLines = new HashSet<ReceiptPlanLines>();
        }
    
        public int ReceiptPlanId { get; set; }
        public int ReceiptPlanStatusId { get; set; }
        public int SupplierId { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string EntryAuthor { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string LastAuthor { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptPlanLines> ReceiptPlanLines { get; set; }
        public virtual ReceiptPlanStatus ReceiptPlanStatus { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
