//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryPlanLines
    {
        public int DeliveryPlanId { get; set; }
        public int DeliveryPlanLineNo { get; set; }
        public int SalesOrderLineNo { get; set; }
        public int ExpectedQty { get; set; }
        public Nullable<int> RecivedQty { get; set; }
        public string EntryAuthor { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string LastAuthor { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual DeliveryPlans DeliveryPlans { get; set; }
        public virtual SalesOrders SalesOrders { get; set; }
    }
}
