//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLineConfirmWms
    {
        public int Id { get; set; }
        public string ReferenceNumber { get; set; }
        public string OrderCode { get; set; }
        public string LogisticSite { get; set; }
        public string OrderLineNo { get; set; }
        public string PartNumber { get; set; }
        public string OrderedQuantity { get; set; }
        public string CheckedQuantity { get; set; }
        public Nullable<System.DateTime> WmsDate { get; set; }
    }
}
