//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptPlanLineConfirmWms
    {
        public int Id { get; set; }
        public string ReferenceNumber { get; set; }
        public string ErCode { get; set; }
        public string LogisticSite { get; set; }
        public string PartNumber { get; set; }
        public string ExpectedQuantity { get; set; }
        public string ReceivedQuantity { get; set; }
        public Nullable<System.DateTime> WmsDate { get; set; }
    }
}
