//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptPlanLines
    {
        public int ReceiptPlanId { get; set; }
        public int ReceiptPlanLineNo { get; set; }
        public int PurchaseOrderId { get; set; }
        public int PurchaseOrderLineNo { get; set; }
        public int ExpectedQty { get; set; }
        public Nullable<int> RecivedQty { get; set; }
        public string EntryAuthor { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string LastAuthor { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual PurchaseOrders PurchaseOrders { get; set; }
        public virtual ReceiptPlans ReceiptPlans { get; set; }
    }
}
