//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderLines
    {
        public int SalesOrderId { get; set; }
        public int SalesOrderLineNo { get; set; }
        public int ProductId { get; set; }
        public int OrderedQty { get; set; }
        public int RecivedQty { get; set; }
        public decimal PurchaseOrderPrice { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string EntryAuthor { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string LastAuthor { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual SalesOrders SalesOrders { get; set; }
    }
}
