//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VPurchaseOrders
    {
        public int PurchaseOrderId { get; set; }
        public int PurchaseOrderStatusId { get; set; }
        public string PurchaseOrderStatus { get; set; }
        public int SupplierId { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> Line { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string CurrencyId { get; set; }
        public decimal CurrencyRate { get; set; }
        public string EntryAuthor { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string LastAuthor { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
