//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VReceiptPlans
    {
        public int ReceiptPlanId { get; set; }
        public string ReceiptPlanStatus { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> Orders { get; set; }
        public Nullable<int> Lines { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string EntryAuthor { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string LastAuthor { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
